SchoolWork/SchoolWork/Controllers/SchoolRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SchoolWork.Models;
using System.Dynamic;
using System.IO;

using System.Net;
using System.Net.Mail;

namespace SchoolWork.Controllers
{
    public class SchoolRegistrationController : Controller

    {
       // DataBaseAcessLayer.StudentAdmissionDB dblayer2 = new DataBaseAcessLayer.StudentAdmissionDB();
        DataBaseAcessLayer.SuperAdminDB dblayer2 = new DataBaseAcessLayer.SuperAdminDB();

        // GET: SchoolRegistration
        public ActionResult SchoolRegister()
        {

            SchoolRegistration model = new SchoolRegistration();
            model.Countries = PopulateDropDown("SELECT CountryId, CountryName FROM country", "CountryName", "CountryId");
            model.Board_Name = PopulateDropDown("SELECT Board_Id, Board_Name FROM Board_Master", "Board_Name", "Board_Id");

            return View(model);

        }




        public ActionResult SchoolLogin()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AjaxMethod(string type, int value)
        {
            SchoolRegistration model = new SchoolRegistration();
            switch (type)
            {
                case "CountryId":
                    model.States = PopulateDropDown("SELECT StateId, StateName FROM state WHERE CountryId = " + value, "StateName", "StateId");
                    break;
                case "StateId":
                    model.Cities = PopulateDropDown("SELECT CityId, CityName FROM city  WHERE StateId = " + value, "CityName", "CityId");
                    break;
            }
            return Json(model);
        }

        [HttpPost]
        public ActionResult SchoolRegister(int countryId, int stateId, int cityId, FormCollection fc)
        {
            SchoolRegistration model = new SchoolRegistration();
            model.Countries = PopulateDropDown("SELECT CountryId, CountryName FROM country", "CountryName", "CountryId");
            model.States = PopulateDropDown("SELECT StateId, StateName FROM state WHERE CountryId = " + countryId, "StateName", "StateId");
            model.Cities = PopulateDropDown("SELECT CityId, CityName FROM city WHERE StateId = " + stateId, "CityName", "CityId");

            try { 

            if (ModelState.IsValid)
            {
                SchoolRegistration stdsch = new SchoolRegistration();
                stdsch.SchoolName = fc["SchoolName"];
                stdsch.SchoolCode = fc["SchoolCode"];
                stdsch.SchoolEmail = fc["SchoolEmail"];
                stdsch.SchoolPassword = fc["SchoolPassword"];
                stdsch.SchoolPhone = fc["SchoolPhone"];
                stdsch.SchoolContactPerson = fc["SchoolContactPerson"];
                stdsch.SchoolContactPersonEmail = fc["SchoolContactPersonEmail"];
                stdsch.SchoolContactPersonPhone = fc["SchoolContactPersonPhone"];
                stdsch.SchoolAddress1 = fc["SchoolAddress1"];
                stdsch.SchoolAddress2 = fc["SchoolAddress2"];
                stdsch.CountryId = Convert.ToInt32(fc["CountryId"]);
                stdsch.StateId = Convert.ToInt32(fc["StateId"]);
                stdsch.CityId = Convert.ToInt32(fc["CityId"]);
                stdsch.Board_Id = Convert.ToInt32(fc["Board_Id"]);
               // stdsch.SchoolAddress1 = fc["SchoolAddress1"];
                //stdsch.SchoolAddress2 = fc["SchoolAddress2"];
                dblayer2.Add_School(stdsch);
                MailMessage mail = new MailMessage("pro@gmail.com", stdsch.SchoolEmail, "mailSubject2", "mailBody2");
                //mail.From = new MailAddress("denovo@gmail.com", "nameEmail aa");
                //mail.IsBodyHtml = true; // necessary if you're using html email
                mail.From = new MailAddress("pro@gmail.com", "Registration Successfull");
                //  mail.Subject = "Hii " + parreg.ParentName +"You are Registered SuccesFully on" + parreg.School_Code +"Your Email Id is"+ parreg.ParentEmail+"And Password is:"+ parreg.ParentPassword+"<br/>";
                mail.Subject = "Registration Successfull";
                mail.Body = "Hii " + stdsch.SchoolName + "You are Registered SuccesFully on  School Days .  Your User \r\n Id: " + stdsch.SchoolEmail + "\r\n  Password:" + stdsch.SchoolPassword + " \r\n ";

                //new MailAddress("pro@gmail.com", "nameEmail aa");
                NetworkCredential credential = new NetworkCredential("schooldays2050@gmail.com", "Marine@1");
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = credential;
                smtp.Send(mail);



                TempData["msg"] = "Student Registration Successful!";
            }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

            }
            return this.RedirectToAction("Startpage", "Home");
           // return View(model);
        }



        private static List<SelectListItem> PopulateDropDown(string query, string textColumn, string valueColumn)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr[textColumn].ToString(),
                                Value = sdr[valueColumn].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return items;
        }


        public JsonResult CheckUsernameAvailability(string useremail)
        {
            System.Threading.Thread.Sleep(200);
            //ParentRegistration model = new ParentRegistration();
            SchoolRegistration model = new SchoolRegistration();
            
            String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(con);
            string sqlquery = "Select School_Email FROM [dbo].[School_Details_Master] WHERE School_Email ='" + useremail + "' ";
            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = sqlcom;
            DataSet ds = new DataSet();
            da.Fill(ds);

            SqlDataReader sdr = sqlcom.ExecuteReader();
            if (sdr.Read())
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }

        }


    }
}

SchoolWork/SchoolWork/Controllers/StudentDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Text.RegularExpressions;
using System.Data.SqlClient;
using System.Configuration;
using SchoolWork.Models;

namespace SchoolWork.Controllers
{
    public class StudentDetailController : Controller
    {

        DataBaseAcessLayer.StudentDetailsDB dblayer2 = new DataBaseAcessLayer.StudentDetailsDB();

        // GET: StudentDetail
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StudentLogin()
        {
            StudentLogin model = new StudentLogin();
            model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");
            return View(model);

        }
        [HttpPost]
        public ActionResult StudentLogin(ParentLogin fc)
        {

            StudentLogin model = new StudentLogin();
            model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");

            try { 
            String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(con);
            // string sqlquery = "Select ParentID,ParentName,ParentEmail, ParentPassword,School_Code FROM [dbo].[ParentRegistration] WHERE  ParentEmail=@Email and ParentPassword=@Password";

            // string sqlquery = "SELECT SM.*,PR.* FROM School_User_Master AS SM, ParentRegistration AS PR WHERE SM.User_Email = @Email AND SM.User_Password =@Password AND SM.School_Code =@School_Code AND SM.User_Type =@User_Type AND SM.User_Id = PR.ParentID AND SM.User_Email = PR.ParentEmail";
            string sqlquery = "SELECT SM.*,SR.*, SDM.* FROM School_User_Master AS SM, School_Student_Details AS SR , School_Details_Master AS SDM WHERE SM.User_Email =@Email AND SM.User_Password =@Password AND SM.School_Code =@School_Code AND SM.User_Type =@User_Type AND SM.User_Id = SR.Student_Id AND SM.User_Email = SR.Student_Email AND SDM.School_Code= SR.School_Code";

            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
            sqlcom.Parameters.AddWithValue("@Email", fc.UserName);
            sqlcom.Parameters.AddWithValue("@Password", fc.Password);
            sqlcom.Parameters.AddWithValue("@School_Code", fc.School_Code);
            sqlcom.Parameters.AddWithValue("@User_Type", fc.User_Type);
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = sqlcom;
            DataSet ds = new DataSet();
            da.Fill(ds);

            SqlDataReader sdr = sqlcom.ExecuteReader();
            if (sdr.Read())
            {
                //Session["username"] = fc.UserName.ToString();
                Session["School_Id"] = ds.Tables[0].Rows[0]["School_Id"].ToString();
                Session["School_Name"] = ds.Tables[0].Rows[0]["School_Name"].ToString();
                Session["School_Code"] = ds.Tables[0].Rows[0]["School_Code"].ToString();
                Session["first_name"] = ds.Tables[0].Rows[0]["first_name"].ToString();
                Session["Student_Id"] = ds.Tables[0].Rows[0]["Student_Id"].ToString();
               // Session["ParentContact"] = ds.Tables[0].Rows[0]["ParentContact"].ToString();
                Session["Student_Email"] = ds.Tables[0].Rows[0]["Student_Email"].ToString();
                Session["Password"] = ds.Tables[0].Rows[0]["Password"].ToString();
                Session["Class_Id"] = ds.Tables[0].Rows[0]["AdmissionClass_Id"].ToString(); 
                Session["Section_Id"] = ds.Tables[0].Rows[0]["Section_Id"].ToString();
                Session["Session_Year"] = ds.Tables[0].Rows[0]["Current_Session_Year"].ToString();
                Session["Section_Id"] = ds.Tables[0].Rows[0]["Section_Id"].ToString();



                    return this.RedirectToAction("StudentHeaderBoard", "Dashboard");
            }
            else
            {
                ViewData["message"] = "Wrong Credentials!";
            }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

            }

            return View(model);
        }



        private static List<SelectListItem> PopulateDropDown(string query, string textColumn, string valueColumn)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr[textColumn].ToString(),
                                Value = sdr[valueColumn].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return items;
        }


        [HttpGet]
        public ActionResult ShowallStudentNotice()
        {

            DataBaseAcessLayer.StudentDetailsDB dbhandle = new DataBaseAcessLayer.StudentDetailsDB();
            return View(dbhandle.GetStudentNotice());

        }

        public ActionResult ShowStudentNoticeDetails(int id)
        {

            DataBaseAcessLayer.StudentDetailsDB dbhandle = new DataBaseAcessLayer.StudentDetailsDB();
            return View(dbhandle.GetStudentNotice().Find(smodel => smodel.Notice_Id == id));

        }

         public ActionResult StudentIndexPage()
        {

            //DataBaseAcessLayer.StudentDetailsDB dbhandle = new DataBaseAcessLayer.StudentDetailsDB();
            // return View(dbhandle.GetStudentNotice());
            return View();
        }

        public ActionResult StudentRegisterBoard()
        {
            StudentRegistration model = new StudentRegistration();
            model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");
            return View(model);

        }


        [HttpPost]
        public ActionResult StudentRegisterBoard(FormCollection fc)
        {

            StudentRegistration model = new StudentRegistration();

            try
            {
                model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");

            String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(con);
            // string sqlquery = "Select ParentID,ParentName,ParentEmail, ParentPassword,School_Code FROM [dbo].[ParentRegistration] WHERE  ParentEmail=@Email and ParentPassword=@Password";

            // string sqlquery = "SELECT SM.*,PR.* FROM School_User_Master AS SM, ParentRegistration AS PR WHERE SM.User_Email = @Email AND SM.User_Password =@Password AND SM.School_Code =@School_Code AND SM.User_Type =@User_Type AND SM.User_Id = PR.ParentID AND SM.User_Email = PR.ParentEmail";
            // string sqlquery = "SELECT SM.*,SR.*, SDM.* FROM School_User_Master AS SM, School_Student_Details AS SR , School_Details_Master AS SDM WHERE SM.User_Email =@Email AND SM.User_Password =@Password AND SM.School_Code =@School_Code AND SM.User_Type =@User_Type AND SM.User_Id = SR.Student_Id AND SM.User_Email = SR.Student_Email AND SDM.School_Code= SR.School_Code";
            string sqlquery = "SELECT SDM.*, S.*, Isnull(S.first_name, '') + ' ' + Isnull(S.middle_name, '') + ' ' + Isnull(S.last_name, '') AS FullName FROM School_Student_Details AS S ,School_Details_Master AS SDM  WHERE S.School_Code =@School_Code AND S.Application_Id=@Application_Id  AND SDM.School_Code=S.School_Code";
            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
            sqlcom.Parameters.AddWithValue("@Application_Id", fc["Application_Id"]);
            //sqlcom.Parameters.AddWithValue("@Password", fc.Password);
            sqlcom.Parameters.AddWithValue("@School_Code", fc["School_Code"]);
            //  sqlcom.Parameters.AddWithValue("@User_Type", fc.User_Type);
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = sqlcom;
            DataSet ds = new DataSet();
            da.Fill(ds);

            SqlDataReader sdr = sqlcom.ExecuteReader();
            if (sdr.Read())
            {
                //Session["username"] = fc.UserName.ToString();
                Session["School_Id"] = ds.Tables[0].Rows[0]["School_Id"].ToString();
                Session["School_Name"] = ds.Tables[0].Rows[0]["School_Name"].ToString();
                Session["School_Code"] = ds.Tables[0].Rows[0]["School_Code"].ToString();
                Session["FullName"] = ds.Tables[0].Rows[0]["FullName"].ToString();
                Session["Application_Id"] = ds.Tables[0].Rows[0]["Application_Id"].ToString();
                Session["Student_Id"] = ds.Tables[0].Rows[0]["Student_Id"].ToString();
                Session["FatherName"] = ds.Tables[0].Rows[0]["FatherName"].ToString();
                Session["FatherContactNumber"] = ds.Tables[0].Rows[0]["FatherContactNumber"].ToString();
                Session["FatherEmail"] = ds.Tables[0].Rows[0]["FatherEmail"].ToString();
                Session["MotherName"] = ds.Tables[0].Rows[0]["MotherName"].ToString();
                Session["MotherContactNumber"] = ds.Tables[0].Rows[0]["MotherContactNumber"].ToString();

SchoolWork/SchoolWork/Views/StudentDetail/ShowStudentNoticeDetails.cshtml
@model SchoolWork.Models.NoticeDetails


<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    @* <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    *@
    <link href="~/CSS/stylesheet2.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }

        h4 {
            text-align: left;
            color: darkcyan;
            margin-left: -10px;
        }
    </style>

</head>
<body id="LoginForm" style="background-color:white">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="container" style="border:1px solid black">

    <h1 style="color:blueviolet; text-align:center"><b>NOTICE INFORMATION</b></h1>
    <br />
    <br />
    <br />
    @Html.HiddenFor(model => model.School_Code)

    <div class="row">
        <div class="col-sm-6">
            <h4>&nbsp;&nbsp; <b>@Html.DisplayName("School Code")</b></h4>

        </div>

    </div>




    <div class="row">
        <div class="col-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.EditorFor(model => model.School_Code, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly"} })
            </div>
            @Html.ValidationMessageFor(model => model.School_Code, "", new { @class = "text-danger" })
        </div>




    </div>


    <div class="row">

        <div class="col-sm-6">
            @* <h4>@Html.LabelFor(model => model.Notice_Id, htmlAttributes: new { @class = "control-label col-md-2" })</h4>*@
            <h4>&nbsp;&nbsp; <b>@Html.DisplayName("Notice Id")</b></h4>
        </div>
        <div class="com-sm-6">

            <h4>&nbsp;&nbsp; <b>@Html.DisplayName("Notice Title")</b></h4>

        </div>

    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="input-group">

                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.EditorFor(model => model.Notice_Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @* @Html.EditorFor(model => model.School_Code)*@

            </div>

            @Html.ValidationMessageFor(model => model.Notice_Id, "", new { @class = "text-danger" })

        </div>

        <div class="col-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.EditorFor(model => model.Notice_Title, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly"} })

            </div>
            @Html.ValidationMessageFor(model => model.Notice_Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <h4>&nbsp;&nbsp; <b>@Html.DisplayName("Notice Description")</b></h4>

        </div>
        <div class="com-sm-6">
            <h4>&nbsp;&nbsp; <b>@Html.DisplayName("Notice Published On")</b></h4>

        </div>

    </div>


    <div class="row">

        <div class="col-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.EditorFor(model => model.Notice_Description, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly"} })
            </div>
            @Html.ValidationMessageFor(model => model.Notice_Description, "", new { @class = "text-danger" })
        </div>


        <div class="col-sm-6">
            <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                @Html.EditorFor(model => model.Notice_Published_On, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly"} })
            </div>
            @Html.ValidationMessageFor(model => model.Notice_Published_On, "", new { @class = "text-danger" })
        </div>

    </div>







    <div class="row">


        <div class="col text-center">
            @* @Html.ActionLink("Back to List", "ShowallAdminNotice")*@

            @*<input type="submit" value="Save" class="btn btn-primary" />*@

            <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-info" />


        </div>

    </div>

</div>

    }



    @section Scripts
            {

        @Scripts.Render("~/bundles/jqueryval")
        @Styles.Render("~/Content/cssjqryUi")




        @* Adding Colours To Daterange picker *@

        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="~/CSS/StyleSheet5.css" rel="stylesheet" />
        <link href="~/CSS/Table.css" rel="stylesheet" />

        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />





        <script>
            $(function () {

                $('input[name="Notice_Published_On"]').daterangepicker(
                    {
                        singleDatePicker: true,
                        timePicker: false,
                        showDropdowns: true,
                        minYear: 2001,

                        locale: {
                            format: 'DD/MM/YYYY'
                        }
                    }


                );

            });
        </script>

        /**/
    }
    /**/

</body>
</html>

SchoolWork/SchoolWork/Views/StudentDetail/ShowallStudentNotice.cshtml
@model IEnumerable<SchoolWork.Models.NoticeDetails>
<h2>NoticeBoard</h2>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/CSS/StyleSheet1.css" rel="stylesheet" />
    <link href="~/CSS/Table.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }
    </style>


</head>

<body id="LoginForm" style="background-color:gainsboro;padding:10px;">

    <h1 class="form-heading"></h1>
    <br />
    <br />
    <br />
    <br />


    <h1 style="color:green; margin-top:-30px; text-align:center"><b>NOTICE BOARD</b></h1>

    <br />
    @if (TempData["msg"] != null)
    {
        <p class="alert alert-success" id="successMessage" style="color:#5cb85c;text-align:center">@TempData["msg"]</p>
    }

        <h3 style="text-align:right;margin-top:-15px">
           
            <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-info" />
        </h3>

        @using (Html.BeginForm("SchoolRegister", "SchoolRegistration", FormMethod.Post, new { id = "myID", name = "randform" }))

        {
            <table class="table" id="products">
                <thead>
                    <tr>
                        <th>@Html.DisplayName("Notice Id")</th>
                        <th>@Html.DisplayName("Notice Title")</th>
                        <th>@Html.DisplayName("Notice Description")</th>
                        <th>@Html.DisplayName("Published On")</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Notice_Id)</td>
                            <td>@Html.DisplayFor(modelItem => item.Notice_Title)</td>
                            <td>@Html.DisplayFor(modelItem => item.Notice_Description)</td>
                            <td>@Html.DisplayFor(modelItem => item.Notice_Published_On)</td>
                            <td>

                                @Html.ActionLink("Details", "ShowStudentNoticeDetails", new { id = item.Notice_Id })

                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        }
        @*</div>*@
        @*</div>
            </div>*@

        @section Scripts
   {
            @Scripts.Render("~/bundles/jqueryval")
            <!-- DataTables CSS -->

            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

            <!-- jQuery -->
            <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

            <!-- DataTables -->
            <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.5/js/jquery.dataTables.js">
            </script>

            <script type="text/javascript" charset="utf8">
                $(document).ready(function () {
                    $('#products').DataTable();
                });
            </script>
        }
</body>



</html>

SchoolWork/SchoolWork/Views/StudentDetail/StudentIndexPage.cshtml
@model SchoolWork.Models.StartPage
@{
    ViewBag.Title = "StudentIndexPage";
}

<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <link href="~/CSS/stylesheet2.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }

        .glyphicon {
            font-size: 30px;
            color: #16E736;
            padding: 10px;
            -webkit-text-stroke: 1px black;
        }

        .col-sm-5 {
            border: 2px solid #3F72F0;
            padding: 10px;
            margin: 10px;
            border-radius: 30px;
        }
    </style>

</head>
<body id="LoginForm" style="background-color:cadetblue">
    <div class="container">
        <h1 class="form-heading"></h1>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <div class="login-form">
            <div class="body-div" style="background-color:aliceblue; max-width:60%">

                <h1 style="color:#C70039; margin-top:-30px;-webkit-text-stroke: 1px black;"><b>SCHOOL ADMIN DASHBOARD </b></h1>



                @if (TempData["msg"] != null)
                {
                    <p class="alert alert-success" id="successMessage" style="color:orangered">@TempData["msg"]</p>
                }
                

                <br>


                <div class="row">
                    <div class="col-sm-5">
                        <div class="input-group">
                            <span class="glyphicon glyphicon-off"></span>


                            @Html.ActionLink("New Registration", "StudentRegisterBoard", "StudentDetail")
                        </div>
                    </div>


                    <div class="col-sm-5">
                        <div class="input-group">
                            <span class="glyphicon glyphicon-off"></span>

                            Already Have a Account!
                            @Html.ActionLink("Sign-In Here", "StudentLogin", "StudentDetail")

                        </div>
                    </div>


                    <br />
                </div>







                <br>


            </div>
        </div>
        <br />
        <br />
    </div>
    @section Scripts
    {
        @Scripts.Render("~/bundles/jqueryval")
    }

</body>
</html>

<script type="text/javascript">


    var colors = ['#FFFF', '#FFFF', '#FFFF', '#FFFF'];

        i = 0;

    $(".body-div").click(function () {
        $(".body-div").css("backgroundColor", colors[i++]);
        if (i >= colors.length)
            i = 0;

    });

</script>