SchoolWork/SchoolWork/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SchoolWork.Models;

namespace SchoolWork.Controllers
{
    public class DashBoardController : Controller
    {
        // GET: DashBoard
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult AdminDashBoard(int id)
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {
                return View(dbhandle.GetAdminWorkRole(id));
            }
        }

        public ActionResult ParentDashBoard(int id)
        {
            if (Session["ParentID"] == null)
            {
                return Redirect("~/ParentDetails/ParentLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetParentWorkRole(id));

            }
        }


        public ActionResult StudentDashBoard(int id)
        {

            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            return View(dbhandle.GetStudentWorkRole(id));

        }


        public ActionResult EmployeeDashBoard(int id)
        {
            //return View();

            //ViewBag.workgroup_id = id;
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetEmployeeWorkRole(id));
            }
        }

        public ActionResult AdminHeaderBoard()
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {
                return View(dbhandle.GetAdminWorkRoleHeader());
            }
            //return View();
        }

        public ActionResult ParentHeaderBoard()
        {
            if (Session["ParentID"] == null)
            {
                return Redirect("~/ParentDetails/ParentLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetParentWorkRoleHeader());
            }
            //return View();
        }

        public ActionResult StudentHeaderBoard()
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            return View(dbhandle.GetStudentWorkRoleHeader());

            //return View();
        }

        public ActionResult EmployeeHeaderBoard()
        {
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetEmployeeWorkRoleHeader());

                //return View();
            }
        }


    }
}

SchoolWork/SchoolWork/Controllers/EmployeeController.cs
using SchoolWork.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Dynamic;
using System.Web.Mvc;
using System.Linq;
using System.Web;
using System.IO;
using System.Text.RegularExpressions;
namespace SchoolWork.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee


        DataBaseAcessLayer.EmployeeDetailsDB dblayer3 = new DataBaseAcessLayer.EmployeeDetailsDB();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EmployeeLogin()
        {
            EmployeeLogin model = new EmployeeLogin();
            model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");
            return View(model);


        }

        [HttpPost]
        public ActionResult EmployeeLogin(ParentLogin fc)
        {
            EmployeeLogin model = new EmployeeLogin();
            model.School_Name = PopulateDropDown("SELECT School_Name,School_Code FROM School_Details_Master", "School_Name", "School_Code");
            try
            {
                String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
                SqlConnection sqlcon = new SqlConnection(con);
                //string sqlquery = "Select Employee_Id,EmpType_Id,Employee_Name, Employee_Code,School_Code,School_Id,School_Name FROM [dbo].[School_Employee_Details] WHERE  Employee_Email=@Email and Employee_Password=@Password";

                sqlcon.Open(); string sqlquery = "SELECT SM.*,PR.* FROM School_User_Master AS SM, School_Employee_Details AS PR WHERE SM.User_Email = @Email AND SM.User_Password =@Password AND SM.School_Code =@School_Code AND SM.User_Type =@User_Type AND SM.User_Id = PR.Employee_Id AND SM.User_Email = PR.Employee_Email";
                SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
                sqlcom.Parameters.AddWithValue("@Email", fc.UserName);
                sqlcom.Parameters.AddWithValue("@Password", fc.Password);
                sqlcom.Parameters.AddWithValue("@School_Code", fc.School_Code);
                sqlcom.Parameters.AddWithValue("@User_Type", fc.User_Type);
                SqlDataAdapter da = new SqlDataAdapter();
                da.SelectCommand = sqlcom;
                DataSet ds = new DataSet();
                da.Fill(ds);

                SqlDataReader sdr = sqlcom.ExecuteReader();
                if (sdr.Read())
                {
                    //Session["username"] = fc.UserName.ToString();
                    Session["Employee_Id"] = ds.Tables[0].Rows[0]["Employee_Id"].ToString();
                    Session["EmpType_Id"] = ds.Tables[0].Rows[0]["EmpType_Id"].ToString();
                    Session["Employee_Name"] = ds.Tables[0].Rows[0]["Employee_Name"].ToString();
                    Session["Employee_Email"] = ds.Tables[0].Rows[0]["Employee_Email"].ToString();
                    Session["Employee_Password"] = ds.Tables[0].Rows[0]["Employee_Password"].ToString();
                    Session["Employee_Code"] = ds.Tables[0].Rows[0]["Employee_Code"].ToString();
                    Session["School_Code"] = ds.Tables[0].Rows[0]["School_Code"].ToString();
                    Session["School_Id"] = ds.Tables[0].Rows[0]["School_Id"].ToString();
                    Session["School_Name"] = ds.Tables[0].Rows[0]["School_Name"].ToString();
                    //ViewData["sucess_msg"] = Session["username"];

                    return this.RedirectToAction("EmployeeHeaderBoard", "Dashboard");

                }

                else
                {
                    ViewData["message"] = "Wrong Credentials!";
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

            }


            return View(model);
        }

        private static List<SelectListItem> PopulateDropDown(string query, string textColumn, string valueColumn)
        {


            List<SelectListItem> items = new List<SelectListItem>();


            string constr = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr[textColumn].ToString(),
                                Value = sdr[valueColumn].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }



            return items;
        }

        [HttpGet]
        public ActionResult ShowallEmpNotice()
        {

            DataBaseAcessLayer.EmployeeDetailsDB dbhandle = new DataBaseAcessLayer.EmployeeDetailsDB();

            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {

                return View(dbhandle.GetEmpNotice());

            }
        }


        [HttpGet]
        public ActionResult ShowNoticeDetails(int id) {

            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            DataBaseAcessLayer.EmployeeDetailsDB dbhandle = new DataBaseAcessLayer.EmployeeDetailsDB();
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                return View(dbhandle.GetEmpNotice().Find(smodel => smodel.Notice_Id == id));
            }

        }
        public ActionResult ShowEmpNoticeDetails(int id)
        {

            DataBaseAcessLayer.EmployeeDetailsDB dbhandle = new DataBaseAcessLayer.EmployeeDetailsDB();
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                return View(dbhandle.GetEmpNotice().Find(smodel => smodel.Notice_Id == id));
            }
        }


        //[HttpGet]
        //public ActionResult ShowaEmpAllDetails()
        //{

        //    DataBaseAcessLayer.EmployeeDetailsDB dbhandle = new DataBaseAcessLayer.EmployeeDetailsDB();
        //    return View(dbhandle.GetEmpAllDetails());
        //}

        //public ActionResult ShowaEmpAllDetails(int id)
        //{

        //    DataBaseAcessLayer.EmployeeDetailsDB dbhandle = new DataBaseAcessLayer.EmployeeDetailsDB();
        //    return View(dbhandle.GetEmpAllDetails().Find(smodel => smodel.Notice_Id == id));
        //}



        public ActionResult StudentAllList()
        {
            dynamic model = new ExpandoObject();
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                model.AllClasses = GetAllClassess();
                model.Students = GetStudents();
                return View(model);
            }

        }


        private static List<ClassesModel> GetAllClassess()
        {
            List<ClassesModel> allclassses = new List<ClassesModel>();

            string query = "SELECT Class_Id, Class_Name FROM Class_Master";
            string constr = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            allclassses.Add(new ClassesModel
                            {
                                Class_Id = Convert.ToInt32(sdr["Class_Id"]),
                                Class_Name = sdr["Class_Name"].ToString(),

                            });
                        }
                    }
                    con.Close();
                    return allclassses;
                }
            }


        }

        private static List<StudentModel> GetStudents()
        {
            List<StudentModel> students = new List<StudentModel>();
            string query = "SELECT ST_Id, (ST_First_Name + ' ' + ST_Last_Name) [Name], SCHL_Code, ST_Class FROM Student_Master";
            string constr = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            students.Add(new StudentModel
                            {
                                //  EmployeeId = sdr["EmployeeID"].ToString(),
                                //   EmployeeName = sdr["Name"].ToString(),
                                // City = sdr["City"].ToString(),
                                // Country = sdr["Country"].ToString()
                                ST_Id = sdr["ST_Id"].ToString(),
                                ST_First_Name = sdr["Name"].ToString(),
                                SCHL_Code = sdr["SCHL_Code"].ToString(),

SchoolWork/SchoolWork/Views/Employee/AddClassNote.cshtml
@model SchoolWork.Models.ClassNoteModule
@{
    ViewBag.Title = "SchoolNoticeAdd";
}
<h2>SchoolNoticeAdd</h2>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    @*<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>*@

    <link href="~/CSS/stylesheet2.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }
    </style>

</head>
<body id="LoginForm" style="background-color:cadetblue">
    <div class="container">
        <h1 class="form-heading"></h1>
        <br />
        <br />
        <br />
        <br />
        <br />
        <div class="login-form">
            <div class="body-div" style="background-color:blanchedalmond; border:2px double light-green; max-width:100%">

                <h1 style="color:blueviolet; margin-top:-30px"><b>CLASS NOTES</b></h1>
                <br />
                <br />

                @if (Session["School_Name"] != null)
                {<p style="font-size:20px;text-align:center">
                     @*   Hi <b style="font-size:20px;color:darkcyan"> @Session["Employee_Name"] </b>*@
                    </p>
                    @*<h1>Hi  @Session["School_Code"] </h1><h1>Hi  @Session["School_Id"] </h1>*@
                }

                @if (TempData["msg"] != null)
                {
                    <p class="alert alert-success" id="successMessage" style="color:orangered">@TempData["msg"]</p>
                }
                <br>




                @using (Html.BeginForm())
                {

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <div class="input-group">

                        @Html.EditorFor(model => model.School_Id, new { htmlAttributes = new { @class = "form-control", @type = "hidden", @onkeydown = "return false", @Value = Session["School_Id"] } })

                    </div>
                    @Html.ValidationMessageFor(model => model.School_Id, "", new { @class = "text-danger" })

                    <div class="input-group">

                        @Html.EditorFor(model => model.Employee_Id, new { htmlAttributes = new { @class = "form-control", @type = "hidden", @onkeydown = "return false", @Value = Session["Employee_Id"] } })

                    </div>
                    @Html.ValidationMessageFor(model => model.Employee_Id, "", new { @class = "text-danger" })

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-barcode"></i></span>
                                @Html.EditorFor(model => model.School_Code, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["School_Code"] } })
                            </div>

                            @Html.ValidationMessageFor(model => model.School_Code, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                @Html.EditorFor(model => model.School_Name, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["School_Name"] } })
                            </div>

                            @Html.ValidationMessageFor(model => model.School_Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                                @Html.DropDownListFor(m => m.Class_Id, Model.Class_Name, "Please select An Class", new { @class = "form-control" })

                            </div>

                            @Html.ValidationMessageFor(m => m.Class_Id, "", new { @class = "text-danger" })

                        </div>

                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                                @Html.DropDownListFor(m => m.Section_Id, Model.Section_Name, "Please select An Section", new { @class = "form-control" })

                            </div>

                            @Html.ValidationMessageFor(m => m.Section_Id, "", new { @class = "text-danger" })

                        </div>

                    </div>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                @Html.EditorFor(model => model.Note_Date, new { htmlAttributes = new { @class = "form-control Note_Date", @Placeholder = "Enter Class Note Published  Date" } })
                            </div>

                            @Html.ValidationMessageFor(model => model.Note_Date, "", new { @class = "text-danger" })

                        </div>


                        <div class="col-sm-4">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                                @Html.DropDownListFor(m => m.Note_Type_Id, Model.Note_Type_Name, "Please select Note Type", new { @class = "form-control" })

                            </div>

                            @*@Html.ValidationMessageFor(m => m.Note_Type_Id, "", new { @class = "text-danger" })*@

                        </div>


                        <div class="col-sm-4">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                                @Html.DropDownListFor(m => m.Subject_Id, Model.Subject_Name, "Please select An Subject", new { @class = "form-control" })

                            </div>

                            @Html.ValidationMessageFor(m => m.Subject_Id, "", new { @class = "text-danger" })

                        </div>



                    </div>


                    <div class="row">
                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-barcode"></i></span>
                                @Html.EditorFor(model => model.Topic_Name, new { htmlAttributes = new { @class = "form-control", @Placeholder = "Enter Class Note  Topic Name Here" } })

                            </div>
                            @Html.ValidationMessageFor(model => model.Topic_Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-sm-6">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-barcode"></i></span>
                                @Html.EditorFor(model => model.Note_Description, new { htmlAttributes = new { @class = "form-control", @Placeholder = "Enter Class Note  Topic Description Here" } })

                            </div>
                            @Html.ValidationMessageFor(model => model.Note_Description, "", new { @class = "text-danger" })
                        </div>

                    </div>



                    <br>

                    <div class="form-group">

                        <input type="submit" value="Submit" class="btn btn-success" />
                        &nbsp;&nbsp;
                        <input type="reset" value="Reset" class="btn btn-warning">
                        &nbsp;&nbsp;

                       @* <input type="button" value="Return" class="btn btn-danger" onclick="@("window.location.href= '"+@ViewBag.PreviousUrl+"' ");" />*@

                        <input type="button" value="Home" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("EmployeeHeaderBoard", "DashBoard") + "'");" />

                        <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-success" />


                    </div>


                }
            </div>
        </div>
    </div>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    @section Scripts
    {
        @Scripts.Render("~/bundles/jqueryval")
        @Styles.Render("~/Content/cssjqryUi")

        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
        <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

        <script type="text/javascript" src="Scripts/jquery_calendar/jquery-ui.js"></script>
        <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
        <script>


            $(function () {
                $(".Note_Date").datepicker(
                    {
                        dateFormat: 'dd/mm/yy',
                        showStatus: true,
                        showWeeks: true,
                        highlightWeek: true,
                        numberOfMonths: 1,
                        showAnim: "scale",
                        showOptions: { origin: ["top", "left"] }
                    }
                );
            });
        </script>
    }
</body>
</html>

SchoolWork/SchoolWork/Views/Employee/ShowallClassNoteData.cshtml
@model IEnumerable<SchoolWork.Models.ClassNoteModule>


<h2>NoticeBoard</h2>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/CSS/StyleSheet1.css" rel="stylesheet" />
    <link href="~/CSS/Table.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }
    </style>


</head>

<body id="LoginForm" style="background-color:gainsboro;padding:10px;">
    @*<div class="container" >*@
    <h1 class="form-heading"></h1>
    <br />
    <br />
    <br />
    <br />
    @*<div class="login-form">
        <div class="body-div" style="border:1px solid black;background-color:gainsboro; max-width:100%">*@

    <h1 style="color:green; margin-top:-30px; text-align:center"><b>CLASS NOTE DETAILS</b></h1>
    <br />

    @if (TempData["msg"] != null)
    {
        <p class="alert alert-success" id="successMessage" style="color:#5cb85c;text-align:center">@TempData["msg"]</p>
    }

        <h3 style="text-align:right;margin-top:-15px">
            <a class="btn btn-primary btn-product" onclick="@("window.location.href='" + @Url.Action("AddClassNote", "Employee") + "'");"><span class="glyphicon glyphicon-pencil"></span>Add New Class Note</a>

            <input type="button" value="Home" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("EmployeeHeaderBoard", "DashBoard") + "'");" />

            <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-success" />

        </h3>

    @using (Html.BeginForm("SchoolRegister", "SchoolRegistration", FormMethod.Post, new { id = "myID", name = "randform" }))

    {

        <table class="table" id="products">
            <thead>
                <tr>
                    <th>@Html.DisplayName(" Note Id")</th>
                    <th>@Html.DisplayName("School Id")</th>
                    <th>@Html.DisplayName("School Code")</th>
                    <th>@Html.DisplayName("School Name")</th>
                    <th>@Html.DisplayName("Class Name")</th>
                    <th>@Html.DisplayName("Section Name")</th>
                    <th>@Html.DisplayName("Subject Name")</th>
                    <th>@Html.DisplayName("Employee Name")</th>
                    <th>@Html.DisplayName("Note Type Name")</th>
                    <th>@Html.DisplayName("Topic Name")</th>
                    <th>@Html.DisplayName("Note Description")</th>
                    <th>@Html.DisplayName("Note Date")</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Note_Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.School_Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.School_Code)</td>
                        <td>@Html.DisplayFor(modelItem => item.School_Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class_Namee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Section_Namee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Subject_Namee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Employee_Namee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Note_Type_Namee)</td>
                        <td>@Html.DisplayFor(modelItem => item.Topic_Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Note_Description)</td>
                        <td>@Html.DisplayFor(modelItem => item.Note_Date)</td>
                        <td>

                            @Html.ActionLink("Details", "NoteDetails", new { id = item.Note_Id })

                            @*@Html.ActionLink("Delete", "DeleteDetails", new { id = item.Note_Id })*@

                            <a onclick="delDetails(this,@item.Note_Id)"><font color="blue"/>Delete</a>


                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    @*</div>*@
    @*</div>
        </div>*@

    @section Scripts
   {
        @Scripts.Render("~/bundles/jqueryval")
        <!-- DataTables CSS -->

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.5/js/jquery.dataTables.js">
        </script>

        <script type="text/javascript" charset="utf8">
            $(document).ready(function () {
                $('#products').DataTable();
            });
            function delDetails(r, id){


                var x = confirm("Do you want to delete?");
                if (x == true) {


                     $.ajax({
                    type: "POST",
                    url: "/Employee/AjaxDelDetails",
                    data: '{id: ' + id+ ' }',

                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    // alert("before");

                         success: function (response) {


                              var i = r.parentNode.parentNode.rowIndex;
                        document.getElementById("products").deleteRow(i);
                       
                        alert(response);

                       




                    },
                    failure: function (response) {
                        alert("from failure" + response.responseText);
                    },
                    error: function (response) {
                        alert("from error  " + response.responseText);
                    }
                });






                }

               // alert(id);

            }





        </script>
    }
</body>



</html>