SchoolWork/SchoolWork/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SchoolWork.Models;

namespace SchoolWork.Controllers
{
    public class DashBoardController : Controller
    {
        // GET: DashBoard
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult AdminDashBoard(int id)
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {
                return View(dbhandle.GetAdminWorkRole(id));
            }
        }

        public ActionResult ParentDashBoard(int id)
        {
            if (Session["ParentID"] == null)
            {
                return Redirect("~/ParentDetails/ParentLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetParentWorkRole(id));

            }
        }


        public ActionResult StudentDashBoard(int id)
        {

            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            return View(dbhandle.GetStudentWorkRole(id));

        }


        public ActionResult EmployeeDashBoard(int id)
        {
            //return View();

            //ViewBag.workgroup_id = id;
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetEmployeeWorkRole(id));
            }
        }

        public ActionResult AdminHeaderBoard()
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {
                return View(dbhandle.GetAdminWorkRoleHeader());
            }
            //return View();
        }

        public ActionResult ParentHeaderBoard()
        {
            if (Session["ParentID"] == null)
            {
                return Redirect("~/ParentDetails/ParentLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetParentWorkRoleHeader());
            }
            //return View();
        }

        public ActionResult StudentHeaderBoard()
        {
            DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
            return View(dbhandle.GetStudentWorkRoleHeader());

            //return View();
        }

        public ActionResult EmployeeHeaderBoard()
        {
            if (Session["Employee_Id"] == null)
            {
                return Redirect("~/Employee/EmployeeLogin");
            }
            else
            {
                DataBaseAcessLayer.BasicDetailsDB dbhandle = new DataBaseAcessLayer.BasicDetailsDB();
                return View(dbhandle.GetEmployeeWorkRoleHeader());

                //return View();
            }
        }


    }
}

SchoolWork/SchoolWork/Controllers/SchoolAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SchoolWork.Models;
using System.Dynamic;
using System.Text.RegularExpressions;
using System.IO;
using System.Net;
using System.Net.Mail;
using CrystalDecisions.Shared;
using CrystalDecisions.ReportSource;
using CrystalDecisions.CrystalReports.Engine;


namespace SchoolWork.Controllers
{
    public class SchoolAdminController : Controller
    {
        //DataBaseAcessLayer.StudentAdmissionDB dblayer2 = new DataBaseAcessLayer.StudentAdmissionDB();
        DataBaseAcessLayer.SchoolAdminDB dblayer3 = new DataBaseAcessLayer.SchoolAdminDB();
        // GET: SchoolAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SchoolAdminLogin()
        {

            return View();


        }


        [HttpPost]
        public ActionResult SchoolAdminLogin(SchoolAdminLogin fc)
        {
            try
            {
                String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
                SqlConnection sqlcon = new SqlConnection(con);
                string sqlquery = "Select School_Id,School_Group_Code,School_Code,School_Name,School_Email, School_Password FROM [dbo].[School_Details_Master] WHERE  School_Email=@Email and School_Password=@Password";
                sqlcon.Open();
                SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
                sqlcom.Parameters.AddWithValue("@Email", fc.UserName);
                sqlcom.Parameters.AddWithValue("@Password", fc.Password);
                SqlDataAdapter da = new SqlDataAdapter();
                da.SelectCommand = sqlcom;
                DataSet ds = new DataSet();
                da.Fill(ds);

                SqlDataReader sdr = sqlcom.ExecuteReader();
                if (sdr.Read())
                {
                    Session["School_Name"] = ds.Tables[0].Rows[0]["School_Name"].ToString();
                    Session["School_Group_Code"] = ds.Tables[0].Rows[0]["School_Group_Code"].ToString();
                    Session["School_Code"] = ds.Tables[0].Rows[0]["School_Code"].ToString();
                    Session["School_Id"] = ds.Tables[0].Rows[0]["School_Id"].ToString();
                    Session["School_Email"] = ds.Tables[0].Rows[0]["School_Email"].ToString();
                    Session["School_Password"] = ds.Tables[0].Rows[0]["School_Password"].ToString();
                   // Session.Timeout = 1;

                    return this.RedirectToAction("AdminHeaderBoard", "Dashboard");
                }
                else
                {
                    ViewData["message"] = "Wrong Credentials!";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

            }

            return View();
        }

        [HttpPost]
        public JsonResult CheckUsernameAvailability(string ClassId, string SubjectName, string School_Code)
        {
           // System.Threading.Thread.Sleep(200);
            ParentRegistration model = new ParentRegistration();
            String con = ConfigurationManager.ConnectionStrings["DataSchoolDB"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(con);
            string sqlquery = "Select Subject_Name FROM [dbo].[School_Subject_Master] WHERE Class_Id = '" + ClassId + "' AND Subject_Name ='" + SubjectName + "' AND School_Code ='" +Session["School_Code"]+ "'  ";

            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);
             SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = sqlcom;
            DataSet ds = new DataSet();
            da.Fill(ds);
            SqlDataReader sdr = sqlcom.ExecuteReader();
            if (sdr.Read())
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }


        }


        public ActionResult StudentGroupMaster()
        {

            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {

                return View();
            }


        }


        [HttpPost]
        public ActionResult StudentGroupMaster(FormCollection fc)
        {
            SchoolAdminModel model = new SchoolAdminModel();
         try { 
            if (ModelState.IsValid)
            {
                StudentGroupMaster stdgrp = new StudentGroupMaster();
                stdgrp.School_Id = Convert.ToInt32(fc["School_Id"]);
                stdgrp.School_Code = fc["School_Code"];
                stdgrp.School_Name = fc["School_Name"];
                stdgrp.Group_Name = fc["Group_Name"];
                dblayer3.Add_Student_Group(stdgrp);

                TempData["msg"] = "Student Group Register Successful!";

                return this.RedirectToAction("AdminDashBoard", "Dashboard");
            }
           }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

            }

            return View(model);
        }

        public ActionResult AddSection()
        {

            SchoolSectionMaster model = new SchoolSectionMaster();
            model.Class_Name = PopulateDropDown("SELECT Class_Id, Class_Name FROM Class_Master WHERE School_Code='" + Session["School_Code"] + "'", "Class_Name", "Class_Id");
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {
                return View(model);
            }

        }

        [HttpPost]
        public ActionResult AddSection(FormCollection fc)
        {
            SchoolAdminModel model = new SchoolAdminModel();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {

                try
                {
                    //if (ModelState.IsValid)
                    //{
                        SchoolSectionMaster schsec = new SchoolSectionMaster();
                        schsec.School_Id = Convert.ToInt32(fc["School_Id"]);
                        schsec.School_Code = fc["School_Code"];
                        schsec.School_Name = fc["School_Name"];
                        schsec.Class_Id = Convert.ToInt32(fc["Class_Id"]);
                        schsec.Section_Name = fc["Section_Name"];
                        schsec.Section_Room_Number = Convert.ToInt32(fc["Section_Room_Number"]);

                        dblayer3.Add_School_Section(schsec);

                        TempData["msg"] = "School Section Created Successfully!";

                        return this.RedirectToAction("AdminHeaderBoard", "Dashboard");
                   // }
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.Message;

                }
                return View(model);
            }
        }

        public ActionResult AddSubject()
        {
            SchoolSubjectMaster model = new SchoolSubjectMaster();
            model.Class_Name = PopulateDropDown("SELECT Class_Id, Class_Name FROM Class_Master", "Class_Name", "Class_Id");
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {

                return View(model);

            }
        }

        [HttpPost]
        public ActionResult AddSubject(FormCollection fc)
        {
            SchoolSubjectMaster model = new SchoolSubjectMaster();
            if (Session["School_Code"] == null)
            {
                return Redirect("~/SchoolAdmin/SchoolAdminLogin");
            }
            else
            {

                try
                {
                    if (ModelState.IsValid)
                    {
                        SchoolSubjectMaster schsub = new SchoolSubjectMaster();
                        schsub.School_Id = Convert.ToInt32(fc["School_Id"]);
                        schsub.School_Code = fc["School_Code"];
                        schsub.School_Name = fc["School_Name"];
                        schsub.Class_Id = Convert.ToInt32(fc["Class_Id"]);
                        schsub.subject_type = fc["subject_type"];
                        if (schsub.subject_type == "A")
                        {
                            schsub.Additional_Subject = "Yes";
                        }
                        schsub.Subject_Name = fc["Subject_Name"];
                        if (!String.IsNullOrEmpty(fc["priority_val"]))
                        {
                            schsub.priority_val = Convert.ToInt32(fc["priority_val"]);
                        }
                        schsub.exam_sub_type = fc["exam_sub_type"];
                        schsub.Subject_Code = fc["Subject_Code"];
                        schsub.FullMarks = Convert.ToInt32(fc["FullMarks"]);
                        if (!String.IsNullOrEmpty(fc["PracticalMarks"]))
                        {
                            schsub.PracticalMarks = Convert.ToInt32(fc["PracticalMarks"]);
                        }
                            schsub.PassMarks = Convert.ToInt32(fc["PassMarks"]);

                        dblayer3.Add_School_Subject(schsub);

                        TempData["msg"] = "School Subject Added Successfully!";

                        return this.RedirectToAction("AdminHeaderBoard", "Dashboard");
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.Message;

                }

                return View(model);
            }

SchoolWork/SchoolWork/Views/ParentDetails/ParentLogin.cshtml
@model SchoolWork.Models.ParentLogin
@{

    ViewBag.Title = "ParentLogin";

}
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <link href="~/CSS/stylesheet2.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }
    </style>

</head>

<body id="LoginForm" style="background-color:cadetblue">
    <div class="container">
        <h1 class="form-heading"></h1>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <div class="login-form">
            <div class="body-div" style="background-color:blanchedalmond;max-width:38%">

                <h1 style="color:blueviolet; margin-top:-30px"><b>PARENTS SIGN-IN HERE</b></h1>
                <br />
                <br />
                @if (@ViewData["message"] != null)
                {
                    <p style="color:orangered"><b>@ViewData["message"]</b></p>
                }

                @using (Html.BeginForm())
                {
                    @Html.HiddenFor(m => m.User_Type, new { Value = "1" })
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="input-group">

                                <span class="input-group-addon"><i class="glyphicon glyphicon-education"></i></span>
                                @Html.DropDownListFor(m => m.School_Code, Model.School_Name, "Please select School", new { @class = "form-control" })

                            </div>

                            @Html.ValidationMessageFor(m => m.School_Code, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    <div class="input-group">

                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @Placeholder = "Enter Your  UserName" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

                    </div>

                    <div class="input-group">

                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type="password", @Placeholder = "Enter Your Password " } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                    </div>


                    <div class="form-group">

                        <input type="submit" value="LogIn" class="btn btn-success" />
                        &nbsp;&nbsp;
                        <input type="reset" value="Reset" class="btn btn-warning">

                    </div>
                    <br>
                    <div class="form-group">

                        <p>Not Registered Yet! <a href="ParentRegister"><b>Click Here To Register</b></a></p>

                    </div>

                }

            </div>
        </div>
    </div>
    @section Scripts
        {

        @Scripts.Render("~/bundles/jqueryval")

    }
</body>
</html>

SchoolWork/SchoolWork/Views/ParentDetails/ShowAllStudentApplication.cshtml
@model IEnumerable<SchoolWork.Models.StudentAdmission>


<h2>NoticeBoard</h2>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/CSS/StyleSheet1.css" rel="stylesheet" />
    <link href="~/CSS/Table.css" rel="stylesheet" />
    <style>
        .text-danger 
        {
            font-weight: 700;
            color: red;
        }
    </style>


</head>

<body id="LoginForm" style="background-color:gainsboro;padding:10px;">
    @*<div class="container" >*@
    <h1 class="form-heading"></h1>
    <br />
    <br />
    <br />
    <br />
    @*<div class="login-form">
        <div class="body-div" style="border:1px solid black;background-color:gainsboro; max-width:100%">*@

    <h1 style="color:green; margin-top:-30px; text-align:center"><b>APPLICATION LISTING</b></h1>

    @if (TempData["msg"] != null)
    {
        <p class="alert alert-success" id="successMessage" style="color:#5cb85c;text-align:center">@TempData["msg"]</p>
    }

        <h3 style="text-align:right;margin-top:-15px">
            <a class="btn btn-primary btn-product" onclick="@("window.location.href='" + @Url.Action("StudentFormFillup", "StudentAdmission") + "'");"><span class="glyphicon glyphicon-pencil"></span>&nbsp; Fill New Application Form</a>

            <input type="button" value="Home" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("ParentHeaderBoard", "DashBoard") + "'");" />

            <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-success" />


        </h3>

    @using (Html.BeginForm("SchoolRegister", "SchoolAdmin", FormMethod.Post, new { id = "myID", name = "randform" }))

    {

        <table class="table" id="products">
            <thead>
                <tr>
                    <th>@Html.DisplayName("Student Id")</th>
                    <th>@Html.DisplayName("School Code")</th>
                    <th>@Html.DisplayName("Full Name")</th>
                    <th>@Html.DisplayName("Father's Name")</th>
                    <th>@Html.DisplayName("Date of Birth")</th>
                    <th>@Html.DisplayName("Gender")</th>
                    <th>@Html.DisplayName("Last School Class")</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Student_Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.School_Code)</td>
                        <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                        <td>@Html.DisplayFor(modelItem => item.FatherName)</td>
                        <td>@Html.DisplayFor(modelItem => item.DOB)</td>
                        <td>@Html.DisplayFor(modelItem => item.Gender_Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.Last_School_Class)</td>
                        <td>

                            @Html.ActionLink("Details", "ShowStudentApplicationDetails", new { id = item.Student_Id })

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    @*</div>*@
    @*</div>
        </div>*@

    @section Scripts
   {
        @Scripts.Render("~/bundles/jqueryval")
        <!-- DataTables CSS -->

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.5/js/jquery.dataTables.js">
        </script>

        <script type="text/javascript" charset="utf8">
            $(document).ready(function () {
                $('#products').DataTable();
            });
        </script>
    }
</body>



</html>

SchoolWork/SchoolWork/Views/ParentDetails/ShowallNotice.cshtml
@model IEnumerable<SchoolWork.Models.NoticeDetails>
<h2>NoticeBoard</h2>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/CSS/StyleSheet1.css" rel="stylesheet" />
    <link href="~/CSS/Table.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-weight: 700;
            color: red;
        }
    </style>


</head>

<body id="LoginForm" style="background-color:gainsboro;padding:10px;">
    @*<div class="container" >*@
    <h1 class="form-heading"></h1>
    <br />
    <br />
    <br />
    <br />
    @*<div class="login-form">
        <div class="body-div" style="border:1px solid black;background-color:gainsboro; max-width:100%">*@

    <h1 style="color:green; margin-top:-30px; text-align:center"><b>NOTICE BOARD</b></h1>
    <br />
    <h3 style="text-align:right;margin-top:-15px">
       
        <input type="button" value="Home" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("ParentHeaderBoard", "DashBoard") + "'");" />

        <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-success" />

    </h3>
    @using (Html.BeginForm("SchoolRegister", "SchoolRegistration", FormMethod.Post, new { id = "myID", name = "randform" }))

    {
        <table class="table" id="products">
            <thead>
                <tr>
                    <th>@Html.DisplayName("Notice Id")</th>
                    <th>@Html.DisplayName("Notice Title")</th>
                    <th>@Html.DisplayName("Notice Description")</th>
                    <th>@Html.DisplayName(" Published On")</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Notice_Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.Notice_Title)</td>
                        <td>@Html.DisplayFor(modelItem => item.Notice_Description)</td>
                        <td>@Html.DisplayFor(modelItem => item.Notice_Published_On)</td>
                        <td>

                            @Html.ActionLink("Details", "ShowNoticeDetails", new { id = item.Notice_Id })

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    }
    @*</div>*@
    @*</div>
        </div>*@

    @section Scripts
   {
        @Scripts.Render("~/bundles/jqueryval")
        <!-- DataTables CSS -->

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

        <!-- jQuery -->
        <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

        <!-- DataTables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.5/js/jquery.dataTables.js">
        </script>

        <script type="text/javascript" charset="utf8">
            $(document).ready(function () {
                $('#products').DataTable();
            });
        </script>
    }
</body>



</html>

SchoolWork/SchoolWork/Views/ParentDetails/UpdateParentInfo.cshtml
@model SchoolWork.Models.ParentDetails

@using (Html.BeginForm())
{
    // @Html.AntiForgeryToken()
    <br />
    <br />
    <br />
    <br />
    <br />


    <div class="form-horizontal">
        <h4>ParentDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentID, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["ParentID"] } })
                @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentName, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["ParentName"] } })
                @Html.ValidationMessageFor(model => model.ParentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentContact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentContact, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["ParentContact"] } })
                @Html.ValidationMessageFor(model => model.ParentContact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ParentEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentEmail, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["ParentEmail"] } })
                @Html.ValidationMessageFor(model => model.ParentEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.School_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.School_Name, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["School_Name"] } })
                @Html.ValidationMessageFor(model => model.School_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.School_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.School_Id, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["School_Id"] } })
                @Html.ValidationMessageFor(model => model.School_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.School_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.School_Code, new { htmlAttributes = new { @class = "form-control", @onkeydown = "return false", @Value = Session["School_Code"] } })
                @Html.ValidationMessageFor(model => model.School_Code, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.ParentPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParentPassword, new { htmlAttributes = new { @class = "form-control", @Value = Session["ParentPassword"] } })
                @Html.ValidationMessageFor(model => model.ParentPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />

                <input type="button" value="Home" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("ParentHeaderBoard", "DashBoard") + "'");" />

                <input type="button" onclick="history.go(-1)" value="Return" class="btn btn-success" />



            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}